[package]
name = "hst-alloc"
version = "0.1.0"
edition = "2018"

[dependencies]
libc = "0.2"
log = { version = "0.4" }
num-traits = "0.2"

[dev-dependencies]
glommio = "0.5"
futures-lite = "1"
rusty-fork = "0.3"
pretty_env_logger = "0.4"
